name = "cloudflare-workers-proxy"
main = "worker.js"
compatibility_date = "2023-08-23"

[env.production]
name = "cloudflare-workers-proxy"
routes = [
  { pattern = "proxy.42783670.xyz", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
URL = "nginx"
